services:
  algorand-node:
    build: .
    image: algorand-node
    container_name: algorand-node
    restart: unless-stopped
    ports:
      - "4190:8080"  # Algorand Node API
      - "4160:4160"  # Algorand Node Client (Goal)
      - "4161:4161"  # Algorand Peer Communication
      - "4191:7833"  # Algorand Node Telemetry
    volumes:
      - ./data:/algod/data       # Persistent data directory for Algorand
      - algorand-logs:/algod/logs       # Persistent log directory for logs
    secrets:
      - ACCOUNT_MNEMONIC
      - ALGOD_TOKEN
      - WALLET_NAME
      - WALLET_PASSWORD
    environment:
      ALGOD_ADDRESS: "http://0.0.0.0:8080"  # Use container-wide accessible address
      NETWORK: "mainnet"
      TELEMETRY_NAME: "algorand-node"
      FAST_CATCHUP: 1
    networks:
      - algorand-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    # ports:
    #   - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - algorand-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - algorand-network

  Wireguard:
    image: linuxserver/wireguard:latest
    container_name: Wireguard
    hostname: WireguardG
    entrypoint: ["/init"]
    privileged: true
    ports:
      - "51820:51820/udp"
    volumes:
      - "$HOME/DATA/Wireguard/config:/config"
    environment:
      - "PGID=1000"
      - "SERVERPORT=51820"
      - "INTERNAL_SUBNET=172.3.0.0/24"
      - "PEERS=10"
      - "PEERDNS=1.1.1.1"
      - "TZ=Europe/Rome"
      - "PUID=1000"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HOME=/root"
      - "TERM=xterm"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
    networks:
      - algorand-network

volumes:
  algorand-data:
    driver: local
  algorand-logs:
    driver: local
  grafana-data:
    driver: local

secrets:
  ACCOUNT_MNEMONIC:
    file: ./secrets/ACCOUNT_MNEMONIC  # Replace with actual path to your secret file
  ALGOD_TOKEN:
    file: ./secrets/ALGOD_TOKEN       # Replace with actual path to your secret file
  WALLET_NAME:
    file: ./secrets/WALLET_NAME       # Replace with actual path to your secret file
  WALLET_PASSWORD:
    file: ./secrets/WALLET_PASSWORD   # Replace with actual path to your secret file

networks:
  algorand-network:
    driver: bridge