global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['algorand-node:9100']
  - job_name: 'algorand'
    static_configs:
      - targets: ['algorand-node:4001']  # Update if you expose additional metrics