FROM grafana/grafana:latest
WORKDIR /etc/grafana/provisioning/

RUN mkdir -p /var/lib/grafana/dashboards
RUN mkdir -p /usr/share/grafana/public/maps

COPY ./datasource-manifest.yaml ./datasources/default.yaml
COPY ./dashboard-provider.yaml ./dashboards/default.yaml
